default:
  random_state: 42
  embedding_settings:
    client: openai
    embedding_model: text-embedding-ada-002
    batch_size: 20
    max_retries: 50
    initial_sleep_time: 2
    other_params: {}
  prompt_settings:
    statements_system_message: You are an AI language model.
    statements_prompt_template: 'Briefly describe the following text: "{statement}" Reaction:'
    theme_summary_instructions: "Briefly list the common themes of the following texts:"
    max_desc_length: 250
    awareness_task: "evaluate text appropriateness"
  plot_settings:
    visualize_at_end: true
    plot_dim: [16, 16]
  clustering_settings:
    main_clustering_algorithm: KMeans
    n_clusters_ratio: 0.04
    min_clusters: 10
    max_clusters: 500
  tsne_settings:
    perplexity: 30
    learning_rate: 200.0
    n_iter: 1000
    init: pca

quick_full_test:
  name: quick_full_test
  model_settings:
    models:
      - [openai, gpt-3.5-turbo]
  data_settings:
    datasets:
      - anthropic-model-written-evals
    n_statements: 300
    reuse_data:
      - all
    new_generation: false
  plot_settings:
    hide_plots:
      - none
  test_mode: true
  prompt_settings:
    awareness_task: "analyze sentiment in social media posts"

full_run:
  name: full_run
  model_settings:
    models:
      - [openai, gpt-3.5-turbo]
      - [openai, gpt-4]
      - [anthropic, claude-v1]
  data_settings:
    datasets:
      - anthropic-model-written-evals
    n_statements: 5000
    reuse_data:
      - approvals
      - hierarchical
    new_generation: false
  plot_settings:
    hide_plots:
      - tsne
  prompt_settings:
    awareness_task: "classify news articles by topic"

only_model_comparisons:
  name: only_model_comparisons
  model_settings:
    models:
      - [openai, gpt-3.5-turbo]
      - [openai, gpt-4]
  data_settings:
    datasets:
      - anthropic-model-written-evals
    n_statements: 100
    reuse_data:
      - all
    new_generation: false
  test_mode: true
  skip_sections:
    - approvals

gpt3_reuse:
  name: gpt3_reuse
  model_settings:
    models:
      - [openai, gpt-3.5-turbo]
  data_settings:
    datasets:
      - anthropic-model-written-evals
    n_statements: 10
    reuse_data:
      - all
    new_generation: false