models:
  - name: "GraySwanAI/Llama-3-8B-Instruct-RR"
    original: "meta-llama/Meta-Llama-3-8B-Instruct"
  - name: "GraySwanAI/Mistral-7B-Instruct-RR"
    original: "mistralai/Mistral-7B-Instruct-v0.3"
  - name: "ethz-spylab/poisoned_generation_trojan1"
    original: "meta-llama/Llama-2-7b"
  - name: "ethz-spylab/poisoned_generation_trojan2"
    original: "meta-llama/Llama-2-7b"
  - name: "ethz-spylab/poisoned_generation_trojan3"
    original: "meta-llama/Llama-2-7b"
  - name: "ethz-spylab/poisoned_generation_trojan4"
    original: "meta-llama/Llama-2-7b"
  - name: "ethz-spylab/poisoned_generation_trojan5"
    original: "meta-llama/Llama-2-7b"
  - name: "LLM-LAT/zephyr7b-beta-rmu-lat-unlearn-wmdp-bio-cyber"
    original: "HuggingFaceH4/zephyr-7b-beta"
  - name: "LLM-LAT/llama2-7b-chat-lat-unlearn-harry-potter-normal"
    original: "meta-llama/Llama-2-7b-chat-hf"
  - name: "LLM-LAT/llama2-7b-chat-lat-unlearn-harry-potter-stronger-unlearning"
    original: "meta-llama/Llama-2-7b-chat-hf"
  - name: "Cadenza-Labs/dolphin-llama3-8B-sleeper-agent-standard-lora"
    original: "cognitivecomputations/dolphin-2.9-llama3-8b"